### PR TITLE
Thumbnail as text in database

### PR DESCRIPTION
**Pull request by smeeckaert**
I've changed the columns onme_thumbnail as a text, since an URL can be longer than 255 characters.

### CODE REVIEW

**Comment by shaoshiva** [comment]
:+1:

**Comment by Meroje** [comment]
:+1:

**Comment by jguyomard** [comment]
nos_page use a varchar(2000) to store url, it's better for performance (a table with text column can't be stored in memory ; text fields are stored off the table, so varchar is faster when the size is small)

**Comment by smeeckaert** [comment]
Better ?

**Comment by jguyomard** [comment]
:+1:

**Comment by Meroje** [comment]
:+1:

**Pull request merged**
