### PR TITLE
new trigger before display onlinemediafiles

### PR DESCRIPTION
**Pull request by ghost**
Hello, I would like to add a new event trigger at the beginning of the display function.
This trigger allows us to modify the params before the display of the embedded online media.

In this particular case it is very useful because we would like to be able to add a new param to the query string of a YouTube video src.

### CODE REVIEW

**Review by jguyomard — APPROVED** [review]

**Comment by Meroje** [comment]
```

**Comment by Meroje** [comment]
You can actually modify the url before displaying the video
```php
<?php
$params_video = array();
if($video->driver()->driverName() == 'Driver_Youtube') {
    $params_video = array (
        'attributes'    => array(
            'src'       => $video->driver()->cleanUrl().'?rel=0'
        )
    );
}
echo $video->display($params_video)
```

**Review by Seb-C — APPROVED** [review]

**Comment by ghost** [comment]
Yes, we thought it could be a possibility, but in that case you must check the driver name throughout the whole site, every time you call the display method.

**Comment by Meroje** [comment]
I'm not a fan of throwing events around, these things could be configurable options

**Comment by ghost** [comment]
@jguyomard @Seb-C Any thoughts on this ?

**Comment by SwithFr** [comment]
:+1: @Meroje

**Review by shaoshiva — APPROVED** [review]

**Pull request merged**
